Features
===========

**1. Cut-Sections**
    - Used to specify the cut-sections that are required to be generated by the
      application.
    - This is an optional section.
    - Only plane sections are supported as of now.
    - User specifies the name of the cut-section and its plane properties.
    - When the name is not specified, it's default value is computed from the
      plane equation.
    - A cut-section can be specified by either specifying the plane equation.


  Examples


  .. admonition:: Specifying Cut-Sections

    ::

      * CUTSECTIONS
      - "X=10", EQUATION="1X=10"
      - EQUATION="1X+1Y+1Z=60"

    - This creates 2 cut-sections in the exported CAX.
    - The First cut-section is defined with equation "1X=10". The same is
      specified to be used as the plane name.
    - The second cut-section is defined with equation "1X+1Y+1Z=60". Since, no
      name is specified for the cut-plane, the plane equation is expected
      to be used as the plane name.
   
