#build TestApp.sln file of test repository from testci repository.

name: Help_Doc

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch.
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    #env: 
    #    PATH: C:\hostedtoolcache\windows\Python\3.6.8\x64\Scripts
       
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2.3.4

      - uses: actions/setup-python@v2
        with:
         python-version: '3.6'
          
      - name: files in python
        run: |
             cd C:\hostedtoolcache\windows\Python\3.6.8\x64
             ls

      - name: Install Sphinx
        run: |
             python -m pip install --upgrade pip
             pip install -U sphinx
             pip install -U sphinx sphinxcontrib-video sphinx_rtd_theme myst-parser

      - name: Run batch file
        run: |
              ./make.bat html

      - name: files in build
        run: |
             cd build\html
             ls
